services:
  web:
    build:
      context: .
    container_name: bloggen_web
    ports:
      - "5000:5000"

  scheduler:
    build:
      context: .
    container_name: bloggen_scheduler
    depends_on:
      - web
    volumes:
      - ./generated:app/generated
    command: >
      sh -c '
        while true; do
          echo "[scheduler] Running daily generation..."
          KEYWORD="wireless earbuds"
          ENCODED=$(echo "$KEYWORD" | jq -sRr @uri)
          curl -s "http://web:5000/generate?keyword=$ENCODED" -o "/app/generated/$(date +%F).json"
          echo "[scheduler] Done. Sleeping for 24h."
          sleep 86400
        done
      '
